/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData airport = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData art_gallery = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData bar = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData baseball = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData basketball = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData beer = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData fast_food = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData ferry = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData fire_station = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData football = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData fuel = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData garden = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData giraffe = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData golf = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData pitch = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData facebook_circled = const IconData(0xf051, fontFamily: _kFontFam);
  static const IconData gplus_circled = const IconData(0xf059, fontFamily: _kFontFam);
  static const IconData gplus = const IconData(0xf05a, fontFamily: _kFontFam);
  static const IconData linkedin_circled = const IconData(0xf05b, fontFamily: _kFontFam);
  static const IconData linkedin = const IconData(0xf05c, fontFamily: _kFontFam);
}
